name: Create New Folder

on:
  push:
    branches:
      - main

jobs:
  create-folder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Create new folder
        run: |
          index=1
          while true; do
            new_folder="new${index}"
            if [ ! -d "$new_folder" ]; then
              mkdir "$new_folder"
              echo "Folder '$new_folder' created successfully."
              break
            fi
            index=$((index + 1))
          done

      - name: Commit and push changes
        run: |
          git config --global user.email "magicalmind01@gmail.com"
          git config --global user.name "shayaliza"
          git add .
          git commit -m "Create $new_folder via GitHub Actions"
          git push
