name: Run Python Script

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # You can add dependencies installation here if needed

      - name: Run Python script and capture output
        id: run-python
        run: |
          output=$(python main.py)
          echo "::set-output name=output::$output"
        working-directory: ${{ github.workspace }}

      - name: Determine new folder name
        id: get-folder-name
        run: |
          folder_name=$(echo "${{ steps.run-python.outputs.output }}" | grep -o "Folder '[^']\+'" | tail -1 | sed "s/^Folder '\(.*\)' created successfully./\1/")
          echo "::set-output name=folder_name::$folder_name"

      - name: Create new folder and commit changes
        if: ${{ steps.get-folder-name.outputs.folder_name != '' }}
        run: |
          git config --global user.email "magicalmind01@gmail.com"
          git config --global user.name "shayaliza"
          mkdir ${{ steps.get-folder-name.outputs.folder_name }}
          git add .
          git commit -m "Create ${{ steps.get-folder-name.outputs.folder_name }} via GitHub Actions"
          git push
