name: Run Python Script

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # You can add dependencies installation here if needed

      - name: Run Python script and capture output
        id: run-python
        run: |
          output=$(python main.py)
          echo "::set-output name=output::$output"
        working-directory: ${{ github.workspace }}

      - name: Print output
        run: echo ${{ steps.run-python.outputs.output }}
